"""
Shadow Trading Monitor

Real-time monitoring and alerting for shadow trading sessions.
Tracks performance, detects anomalies, and manages automated responses.

Features:
- Real-time performance tracking
- Drawdown alerts and circuit breakers
- Anomaly detection (regime changes, unusual losses)
- Health checks and diagnostics
"""

from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Any, Callable, Set
from enum import Enum
import logging
from collections import defaultdict, deque
import statistics

from shared.unified_strategy import UnifiedStrategy
from shared.constants import FORWARD_TEST_CONFIG

from .models import (
    Position,
    Trade,
    VolatilityRegime,
    MarketState,
)
from .analytics.performance import PerformanceMetrics

logger = logging.getLogger(__name__)


# ==============================================================================
# Alert System
# ==============================================================================

class AlertLevel(Enum):
    """Alert severity levels."""
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"
    EMERGENCY = "EMERGENCY"


class AlertType(Enum):
    """Types of monitoring alerts."""
    # Performance alerts
    DRAWDOWN_WARNING = "DRAWDOWN_WARNING"
    DRAWDOWN_CRITICAL = "DRAWDOWN_CRITICAL"
    LOSING_STREAK = "LOSING_STREAK"
    PERFORMANCE_DEGRADATION = "PERFORMANCE_DEGRADATION"
    TRANSFER_RATIO_LOW = "TRANSFER_RATIO_LOW"

    # Execution alerts
    HIGH_SLIPPAGE = "HIGH_SLIPPAGE"
    EXECUTION_FAILURE = "EXECUTION_FAILURE"
    ORDER_REJECTION = "ORDER_REJECTION"

    # System alerts
    REGIME_CHANGE = "REGIME_CHANGE"
    VOLATILITY_SPIKE = "VOLATILITY_SPIKE"
    LIQUIDITY_WARNING = "LIQUIDITY_WARNING"

    # Lifecycle alerts
    SESSION_STARTED = "SESSION_STARTED"
    SESSION_COMPLETED = "SESSION_COMPLETED"
    SESSION_FAILED = "SESSION_FAILED"
    DURATION_MILESTONE = "DURATION_MILESTONE"

    # Health alerts
    STALE_DATA = "STALE_DATA"
    CONNECTION_ISSUE = "CONNECTION_ISSUE"
    HEALTH_CHECK_FAILED = "HEALTH_CHECK_FAILED"


@dataclass
class MonitorAlert:
    """Alert generated by the monitor."""
    id: str = ""
    strategy_id: str = ""
    alert_type: AlertType = AlertType.PERFORMANCE_DEGRADATION
    level: AlertLevel = AlertLevel.INFO

    # Alert details
    message: str = ""
    details: Dict[str, Any] = field(default_factory=dict)

    # Context
    current_value: float = 0.0
    threshold_value: float = 0.0

    # Timing
    timestamp: datetime = field(default_factory=datetime.now)
    acknowledged: bool = False
    acknowledged_at: Optional[datetime] = None

    # Actions taken
    auto_action: Optional[str] = None
    action_result: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            'id': self.id,
            'strategy_id': self.strategy_id,
            'alert_type': self.alert_type.value,
            'level': self.level.value,
            'message': self.message,
            'details': self.details,
            'current_value': self.current_value,
            'threshold_value': self.threshold_value,
            'timestamp': self.timestamp.isoformat(),
            'acknowledged': self.acknowledged,
            'auto_action': self.auto_action,
        }


# ==============================================================================
# Monitor Configuration
# ==============================================================================

@dataclass
class MonitorConfig:
    """Configuration for shadow monitor."""

    # Drawdown thresholds
    drawdown_warning_pct: float = 10.0  # Warn at 10% DD
    drawdown_critical_pct: float = 15.0  # Critical at 15% DD
    drawdown_emergency_pct: float = 20.0  # Emergency at 20% DD

    # Performance thresholds
    losing_streak_warning: int = 5  # Warn after 5 consecutive losses
    losing_streak_critical: int = 8  # Critical after 8
    max_daily_loss_pct: float = 5.0  # Max 5% daily loss

    # Transfer ratio monitoring
    transfer_ratio_warning: float = 0.6  # Warn if ratio drops below 0.6
    transfer_ratio_critical: float = 0.4  # Critical below 0.4

    # Execution quality
    slippage_warning_bps: float = 15.0  # Warn at 15 bps avg
    slippage_critical_bps: float = 30.0  # Critical at 30 bps
    max_rejection_rate: float = 0.10  # Max 10% order rejections

    # Data freshness
    stale_data_seconds: int = 300  # Alert if no update for 5 min
    health_check_interval_seconds: int = 60

    # Auto-actions
    auto_pause_on_drawdown_emergency: bool = True
    auto_pause_on_losing_streak: bool = False
    notify_on_regime_change: bool = True

    # Milestones
    duration_milestones_days: List[int] = field(default_factory=lambda: [1, 7, 14, 21])
    trade_milestones: List[int] = field(default_factory=lambda: [10, 30, 50, 100])


# ==============================================================================
# Strategy Health Tracker
# ==============================================================================

@dataclass
class StrategyHealth:
    """Health status for a single strategy."""
    strategy_id: str = ""

    # Current metrics
    current_pnl: float = 0.0
    current_drawdown_pct: float = 0.0
    current_sharpe: float = 0.0
    transfer_ratio: float = 0.0

    # Trade tracking
    total_trades: int = 0
    winning_trades: int = 0
    consecutive_losses: int = 0
    consecutive_wins: int = 0

    # Daily tracking
    daily_pnl: float = 0.0
    daily_trades: int = 0
    daily_start_equity: float = 0.0

    # Execution quality
    avg_slippage_bps: float = 0.0
    rejection_count: int = 0
    total_orders: int = 0

    # Timing
    last_trade_time: Optional[datetime] = None
    last_update_time: datetime = field(default_factory=datetime.now)
    session_start: datetime = field(default_factory=datetime.now)

    # Status
    is_healthy: bool = True
    is_paused: bool = False
    warnings: List[str] = field(default_factory=list)

    # Recent trades (rolling window)
    recent_pnl: deque = field(default_factory=lambda: deque(maxlen=20))

    @property
    def duration_days(self) -> float:
        return (datetime.now() - self.session_start).total_seconds() / 86400

    @property
    def win_rate(self) -> float:
        return self.winning_trades / self.total_trades if self.total_trades > 0 else 0

    @property
    def rejection_rate(self) -> float:
        return self.rejection_count / self.total_orders if self.total_orders > 0 else 0


# ==============================================================================
# Shadow Monitor
# ==============================================================================

class ShadowMonitor:
    """
    Real-time monitoring system for shadow trading sessions.

    Features:
    - Performance tracking with configurable thresholds
    - Alert generation and escalation
    - Automated responses (pause, notify)
    - Health diagnostics

    Usage:
        monitor = ShadowMonitor()

        # Register strategy
        monitor.register_strategy(strategy_id)

        # Update with new trade
        monitor.on_trade(strategy_id, trade)

        # Get alerts
        alerts = monitor.get_alerts(strategy_id)

        # Health check
        health = monitor.get_health(strategy_id)
    """

    def __init__(self, config: Optional[MonitorConfig] = None):
        """
        Initialize shadow monitor.

        Args:
            config: Monitor configuration
        """
        self.config = config or MonitorConfig()

        # Tracked strategies
        self.strategies: Dict[str, StrategyHealth] = {}

        # Alert storage
        self.alerts: Dict[str, List[MonitorAlert]] = defaultdict(list)
        self.alert_counter = 0

        # Regime tracking
        self.current_regime: VolatilityRegime = VolatilityRegime.NORMAL
        self.regime_history: List[Tuple[datetime, VolatilityRegime]] = []

        # Callbacks
        self.on_alert_callback: Optional[Callable[[MonitorAlert], None]] = None
        self.on_pause_callback: Optional[Callable[[str], None]] = None

        # Statistics
        self.total_alerts = 0
        self.alerts_by_level: Dict[AlertLevel, int] = defaultdict(int)
        self.alerts_by_type: Dict[AlertType, int] = defaultdict(int)

        logger.info("ShadowMonitor initialized")

    def register_strategy(
        self,
        strategy_id: str,
        initial_equity: float = 100000.0,
        backtest_sharpe: float = 0.0,
    ) -> None:
        """
        Register a strategy for monitoring.

        Args:
            strategy_id: Strategy to monitor
            initial_equity: Starting equity
            backtest_sharpe: Reference Sharpe from backtest
        """
        health = StrategyHealth(
            strategy_id=strategy_id,
            daily_start_equity=initial_equity,
            session_start=datetime.now(),
        )

        self.strategies[strategy_id] = health

        # Emit session started alert
        self._emit_alert(
            strategy_id=strategy_id,
            alert_type=AlertType.SESSION_STARTED,
            level=AlertLevel.INFO,
            message=f"Shadow trading session started for {strategy_id}",
        )

        logger.info(f"Registered strategy {strategy_id} for monitoring")

    def unregister_strategy(self, strategy_id: str) -> None:
        """Unregister a strategy from monitoring."""
        if strategy_id in self.strategies:
            del self.strategies[strategy_id]
            logger.info(f"Unregistered strategy {strategy_id}")

    def on_trade(
        self,
        strategy_id: str,
        pnl: float,
        slippage_bps: float = 0.0,
        is_win: bool = False,
    ) -> List[MonitorAlert]:
        """
        Process a new trade and check for alerts.

        Args:
            strategy_id: Strategy that traded
            pnl: Trade P&L
            slippage_bps: Slippage in basis points
            is_win: Whether trade was profitable

        Returns:
            List of alerts triggered
        """
        health = self.strategies.get(strategy_id)
        if not health:
            return []

        alerts = []

        # Update metrics
        health.total_trades += 1
        health.daily_trades += 1
        health.current_pnl += pnl
        health.daily_pnl += pnl
        health.recent_pnl.append(pnl)
        health.last_trade_time = datetime.now()
        health.last_update_time = datetime.now()

        if is_win:
            health.winning_trades += 1
            health.consecutive_wins += 1
            health.consecutive_losses = 0
        else:
            health.consecutive_losses += 1
            health.consecutive_wins = 0

        # Update slippage tracking (rolling average)
        n = health.total_trades
        health.avg_slippage_bps = ((n - 1) * health.avg_slippage_bps + slippage_bps) / n

        # Check for alerts
        alerts.extend(self._check_losing_streak(health))
        alerts.extend(self._check_slippage(health))

        # Check trade milestones
        alerts.extend(self._check_milestones(health))

        return alerts

    def on_equity_update(
        self,
        strategy_id: str,
        equity: float,
        initial_equity: float,
    ) -> List[MonitorAlert]:
        """
        Process equity update and check drawdown.

        Args:
            strategy_id: Strategy ID
            equity: Current equity
            initial_equity: Starting equity

        Returns:
            List of alerts triggered
        """
        health = self.strategies.get(strategy_id)
        if not health:
            return []

        alerts = []

        # Calculate drawdown
        peak = max(initial_equity, health.daily_start_equity)
        drawdown_pct = ((peak - equity) / peak) * 100 if peak > 0 else 0

        health.current_drawdown_pct = drawdown_pct
        health.last_update_time = datetime.now()

        # Check drawdown alerts
        alerts.extend(self._check_drawdown(health))

        return alerts

    def on_performance_update(
        self,
        strategy_id: str,
        sharpe: float,
        backtest_sharpe: float,
    ) -> List[MonitorAlert]:
        """
        Process performance metrics update.

        Args:
            strategy_id: Strategy ID
            sharpe: Current Sharpe ratio
            backtest_sharpe: Reference backtest Sharpe

        Returns:
            List of alerts triggered
        """
        health = self.strategies.get(strategy_id)
        if not health:
            return []

        alerts = []

        health.current_sharpe = sharpe

        # Calculate transfer ratio
        if backtest_sharpe > 0:
            health.transfer_ratio = sharpe / backtest_sharpe
        else:
            health.transfer_ratio = 0.0

        health.last_update_time = datetime.now()

        # Check transfer ratio
        alerts.extend(self._check_transfer_ratio(health))

        return alerts

    def on_order_result(
        self,
        strategy_id: str,
        success: bool,
        rejection_reason: Optional[str] = None,
    ) -> List[MonitorAlert]:
        """
        Process order execution result.

        Args:
            strategy_id: Strategy ID
            success: Whether order succeeded
            rejection_reason: Reason if rejected

        Returns:
            List of alerts triggered
        """
        health = self.strategies.get(strategy_id)
        if not health:
            return []

        alerts = []

        health.total_orders += 1
        if not success:
            health.rejection_count += 1

            # Check rejection rate
            if health.rejection_rate > self.config.max_rejection_rate:
                alerts.append(self._emit_alert(
                    strategy_id=strategy_id,
                    alert_type=AlertType.ORDER_REJECTION,
                    level=AlertLevel.WARNING,
                    message=f"High order rejection rate: {health.rejection_rate:.1%}",
                    current_value=health.rejection_rate,
                    threshold_value=self.config.max_rejection_rate,
                    details={'rejection_reason': rejection_reason},
                ))

        return alerts

    def on_regime_change(self, new_regime: VolatilityRegime) -> List[MonitorAlert]:
        """
        Process market regime change.

        Args:
            new_regime: New volatility regime

        Returns:
            List of alerts triggered (one per monitored strategy)
        """
        if new_regime == self.current_regime:
            return []

        old_regime = self.current_regime
        self.current_regime = new_regime
        self.regime_history.append((datetime.now(), new_regime))

        alerts = []

        if self.config.notify_on_regime_change:
            # Determine alert level based on regime severity
            # LOW_VOL and NORMAL are calm - INFO level
            # HIGH_VOL, CRISIS, CASCADE are concerning - WARNING level
            calm_regimes = {VolatilityRegime.LOW_VOL, VolatilityRegime.NORMAL}
            alert_level = AlertLevel.INFO if new_regime in calm_regimes else AlertLevel.WARNING

            # Alert all strategies
            for strategy_id in self.strategies:
                alerts.append(self._emit_alert(
                    strategy_id=strategy_id,
                    alert_type=AlertType.REGIME_CHANGE,
                    level=alert_level,
                    message=f"Market regime changed: {old_regime.value} -> {new_regime.value}",
                    details={'old_regime': old_regime.value, 'new_regime': new_regime.value},
                ))

        return alerts

    def health_check(self, strategy_id: str) -> Dict[str, Any]:
        """
        Perform health check on a strategy.

        Args:
            strategy_id: Strategy to check

        Returns:
            Health check results
        """
        health = self.strategies.get(strategy_id)
        if not health:
            return {'status': 'not_found', 'strategy_id': strategy_id}

        issues = []

        # Check data freshness
        data_age = (datetime.now() - health.last_update_time).total_seconds()
        if data_age > self.config.stale_data_seconds:
            issues.append(f"Stale data: {data_age:.0f}s since last update")
            self._emit_alert(
                strategy_id=strategy_id,
                alert_type=AlertType.STALE_DATA,
                level=AlertLevel.WARNING,
                message=f"No updates for {data_age:.0f} seconds",
            )

        # Check overall health
        health.is_healthy = len(issues) == 0 and not health.is_paused

        return {
            'status': 'healthy' if health.is_healthy else 'unhealthy',
            'strategy_id': strategy_id,
            'issues': issues,
            'metrics': {
                'duration_days': health.duration_days,
                'total_trades': health.total_trades,
                'win_rate': health.win_rate,
                'current_drawdown_pct': health.current_drawdown_pct,
                'transfer_ratio': health.transfer_ratio,
                'avg_slippage_bps': health.avg_slippage_bps,
            },
            'is_paused': health.is_paused,
            'last_update': health.last_update_time.isoformat(),
        }

    def get_health(self, strategy_id: str) -> Optional[StrategyHealth]:
        """Get health status for a strategy."""
        return self.strategies.get(strategy_id)

    def get_alerts(
        self,
        strategy_id: Optional[str] = None,
        level: Optional[AlertLevel] = None,
        unacknowledged_only: bool = False,
        limit: int = 100,
    ) -> List[MonitorAlert]:
        """
        Get alerts with optional filtering.

        Args:
            strategy_id: Filter by strategy (None for all)
            level: Filter by alert level
            unacknowledged_only: Only return unacknowledged alerts
            limit: Maximum alerts to return

        Returns:
            List of matching alerts
        """
        all_alerts = []

        if strategy_id:
            all_alerts = self.alerts.get(strategy_id, [])
        else:
            for alerts in self.alerts.values():
                all_alerts.extend(alerts)

        # Filter
        if level:
            all_alerts = [a for a in all_alerts if a.level == level]

        if unacknowledged_only:
            all_alerts = [a for a in all_alerts if not a.acknowledged]

        # Sort by timestamp (newest first)
        all_alerts.sort(key=lambda a: a.timestamp, reverse=True)

        return all_alerts[:limit]

    def acknowledge_alert(self, alert_id: str) -> bool:
        """Acknowledge an alert."""
        for alerts in self.alerts.values():
            for alert in alerts:
                if alert.id == alert_id:
                    alert.acknowledged = True
                    alert.acknowledged_at = datetime.now()
                    return True
        return False

    def pause_strategy(self, strategy_id: str, reason: str) -> None:
        """Pause a strategy (from monitor)."""
        health = self.strategies.get(strategy_id)
        if health:
            health.is_paused = True
            health.warnings.append(f"Paused: {reason}")

            if self.on_pause_callback:
                self.on_pause_callback(strategy_id)

            logger.warning(f"Monitor paused strategy {strategy_id}: {reason}")

    def resume_strategy(self, strategy_id: str) -> None:
        """Resume a paused strategy."""
        health = self.strategies.get(strategy_id)
        if health:
            health.is_paused = False
            logger.info(f"Monitor resumed strategy {strategy_id}")

    def reset_daily(self) -> None:
        """Reset daily tracking (call at start of each trading day)."""
        for health in self.strategies.values():
            health.daily_pnl = 0.0
            health.daily_trades = 0
            health.daily_start_equity = health.daily_start_equity + health.daily_pnl

    def _check_drawdown(self, health: StrategyHealth) -> List[MonitorAlert]:
        """Check drawdown thresholds."""
        alerts = []
        dd = health.current_drawdown_pct

        if dd >= self.config.drawdown_emergency_pct:
            alert = self._emit_alert(
                strategy_id=health.strategy_id,
                alert_type=AlertType.DRAWDOWN_CRITICAL,
                level=AlertLevel.EMERGENCY,
                message=f"EMERGENCY: Drawdown at {dd:.1f}%",
                current_value=dd,
                threshold_value=self.config.drawdown_emergency_pct,
            )
            alerts.append(alert)

            # Auto-pause if configured
            if self.config.auto_pause_on_drawdown_emergency:
                self.pause_strategy(health.strategy_id, "Emergency drawdown limit")
                alert.auto_action = "PAUSED"

        elif dd >= self.config.drawdown_critical_pct:
            alerts.append(self._emit_alert(
                strategy_id=health.strategy_id,
                alert_type=AlertType.DRAWDOWN_CRITICAL,
                level=AlertLevel.CRITICAL,
                message=f"Critical drawdown: {dd:.1f}%",
                current_value=dd,
                threshold_value=self.config.drawdown_critical_pct,
            ))

        elif dd >= self.config.drawdown_warning_pct:
            alerts.append(self._emit_alert(
                strategy_id=health.strategy_id,
                alert_type=AlertType.DRAWDOWN_WARNING,
                level=AlertLevel.WARNING,
                message=f"Drawdown warning: {dd:.1f}%",
                current_value=dd,
                threshold_value=self.config.drawdown_warning_pct,
            ))

        return alerts

    def _check_losing_streak(self, health: StrategyHealth) -> List[MonitorAlert]:
        """Check losing streak thresholds."""
        alerts = []
        streak = health.consecutive_losses

        if streak >= self.config.losing_streak_critical:
            alert = self._emit_alert(
                strategy_id=health.strategy_id,
                alert_type=AlertType.LOSING_STREAK,
                level=AlertLevel.CRITICAL,
                message=f"Critical losing streak: {streak} consecutive losses",
                current_value=float(streak),
                threshold_value=float(self.config.losing_streak_critical),
            )
            alerts.append(alert)

            if self.config.auto_pause_on_losing_streak:
                self.pause_strategy(health.strategy_id, "Losing streak limit")
                alert.auto_action = "PAUSED"

        elif streak >= self.config.losing_streak_warning:
            alerts.append(self._emit_alert(
                strategy_id=health.strategy_id,
                alert_type=AlertType.LOSING_STREAK,
                level=AlertLevel.WARNING,
                message=f"Losing streak warning: {streak} consecutive losses",
                current_value=float(streak),
                threshold_value=float(self.config.losing_streak_warning),
            ))

        return alerts

    def _check_slippage(self, health: StrategyHealth) -> List[MonitorAlert]:
        """Check slippage thresholds."""
        alerts = []
        slippage = health.avg_slippage_bps

        if slippage >= self.config.slippage_critical_bps:
            alerts.append(self._emit_alert(
                strategy_id=health.strategy_id,
                alert_type=AlertType.HIGH_SLIPPAGE,
                level=AlertLevel.CRITICAL,
                message=f"Critical slippage: {slippage:.1f} bps average",
                current_value=slippage,
                threshold_value=self.config.slippage_critical_bps,
            ))

        elif slippage >= self.config.slippage_warning_bps:
            alerts.append(self._emit_alert(
                strategy_id=health.strategy_id,
                alert_type=AlertType.HIGH_SLIPPAGE,
                level=AlertLevel.WARNING,
                message=f"High slippage: {slippage:.1f} bps average",
                current_value=slippage,
                threshold_value=self.config.slippage_warning_bps,
            ))

        return alerts

    def _check_transfer_ratio(self, health: StrategyHealth) -> List[MonitorAlert]:
        """Check transfer ratio thresholds."""
        alerts = []
        ratio = health.transfer_ratio

        if ratio < self.config.transfer_ratio_critical:
            alerts.append(self._emit_alert(
                strategy_id=health.strategy_id,
                alert_type=AlertType.TRANSFER_RATIO_LOW,
                level=AlertLevel.CRITICAL,
                message=f"Transfer ratio critically low: {ratio:.2f}",
                current_value=ratio,
                threshold_value=self.config.transfer_ratio_critical,
            ))

        elif ratio < self.config.transfer_ratio_warning:
            alerts.append(self._emit_alert(
                strategy_id=health.strategy_id,
                alert_type=AlertType.TRANSFER_RATIO_LOW,
                level=AlertLevel.WARNING,
                message=f"Transfer ratio low: {ratio:.2f}",
                current_value=ratio,
                threshold_value=self.config.transfer_ratio_warning,
            ))

        return alerts

    def _check_milestones(self, health: StrategyHealth) -> List[MonitorAlert]:
        """Check for duration and trade milestones."""
        alerts = []

        # Duration milestones
        for days in self.config.duration_milestones_days:
            if abs(health.duration_days - days) < 0.1:  # Within ~2.4 hours
                alerts.append(self._emit_alert(
                    strategy_id=health.strategy_id,
                    alert_type=AlertType.DURATION_MILESTONE,
                    level=AlertLevel.INFO,
                    message=f"Duration milestone: {days} days",
                    current_value=health.duration_days,
                    threshold_value=float(days),
                ))

        # Trade milestones
        if health.total_trades in self.config.trade_milestones:
            alerts.append(self._emit_alert(
                strategy_id=health.strategy_id,
                alert_type=AlertType.DURATION_MILESTONE,
                level=AlertLevel.INFO,
                message=f"Trade milestone: {health.total_trades} trades",
                current_value=float(health.total_trades),
                threshold_value=float(health.total_trades),
            ))

        return alerts

    def _emit_alert(
        self,
        strategy_id: str,
        alert_type: AlertType,
        level: AlertLevel,
        message: str,
        current_value: float = 0.0,
        threshold_value: float = 0.0,
        details: Optional[Dict[str, Any]] = None,
    ) -> MonitorAlert:
        """Create and emit an alert."""
        self.alert_counter += 1

        alert = MonitorAlert(
            id=f"alert_{self.alert_counter}",
            strategy_id=strategy_id,
            alert_type=alert_type,
            level=level,
            message=message,
            current_value=current_value,
            threshold_value=threshold_value,
            details=details or {},
            timestamp=datetime.now(),
        )

        # Store
        self.alerts[strategy_id].append(alert)
        self.total_alerts += 1
        self.alerts_by_level[level] += 1
        self.alerts_by_type[alert_type] += 1

        # Callback
        if self.on_alert_callback:
            self.on_alert_callback(alert)

        # Log
        log_level = {
            AlertLevel.INFO: logging.INFO,
            AlertLevel.WARNING: logging.WARNING,
            AlertLevel.CRITICAL: logging.ERROR,
            AlertLevel.EMERGENCY: logging.CRITICAL,
        }.get(level, logging.INFO)

        logger.log(log_level, f"[{strategy_id}] {level.value}: {message}")

        return alert

    def get_statistics(self) -> Dict[str, Any]:
        """Get monitor statistics."""
        return {
            'strategies_monitored': len(self.strategies),
            'total_alerts': self.total_alerts,
            'alerts_by_level': {k.value: v for k, v in self.alerts_by_level.items()},
            'alerts_by_type': {k.value: v for k, v in self.alerts_by_type.items()},
            'current_regime': self.current_regime.value,
            'paused_strategies': sum(1 for h in self.strategies.values() if h.is_paused),
        }
