"""
Unified Strategy Format for EXPLORER PRIME

This module defines the canonical strategy representation that flows through
the entire pipeline:
- Generation (Explorer v3.0, LSM)
- Validation (HIFA v2.0)
- Forward Testing (Hinance)
- Production Storage (EMT)

Key Classes:
- StrategyGenome: Core strategy logic representation
- UnifiedStrategy: Complete strategy package with metadata
- HIFAResult: Historical validation results
- ForwardTestResult: Live testing results
- ProductionStrategy: Final production-ready strategy
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any, Tuple
from datetime import datetime
from enum import Enum
import json
import hashlib
import uuid


class StrategyStatus(Enum):
    """Strategy lifecycle status."""
    GENERATED = "generated"           # Just created
    HIFA_VALIDATING = "hifa_validating"  # In HIFA pipeline
    HIFA_PASSED = "hifa_passed"       # Passed HIFA
    HIFA_FAILED = "hifa_failed"       # Failed HIFA
    SHADOW_TRADING = "shadow_trading"  # In forward testing
    FORWARD_PASSED = "forward_passed"  # Passed forward testing
    FORWARD_FAILED = "forward_failed"  # Failed forward testing
    PRODUCTION = "production"         # Active in production
    MONITORING = "monitoring"         # Under performance watch
    RETIRED = "retired"               # Retired from production


class SourceEngine(Enum):
    """Strategy generation source."""
    EVOLUTIONARY = "evolutionary"
    GENAI = "genai"
    PATTERN = "pattern"
    RECOMBINE = "recombine"
    LSM = "lsm"
    MANUAL = "manual"
    EXTERNAL = "external"


class RegimeTier(Enum):
    """Strategy regime classification."""
    ALL_WEATHER = "all_weather"       # Works in all regimes
    REGIME_SPECIFIC = "regime_specific"  # Only works in specific regimes
    UNKNOWN = "unknown"


# ==============================================================================
# Strategy Genome (Core Logic)
# ==============================================================================

@dataclass
class ConditionNode:
    """Single condition in strategy logic tree."""
    operator: str                     # "and", "or", "gt", "lt", "eq", etc.
    left: Any                         # Left operand (indicator, value, or nested node)
    right: Any                        # Right operand
    children: List['ConditionNode'] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "operator": self.operator,
            "left": self.left if not isinstance(self.left, ConditionNode) else self.left.to_dict(),
            "right": self.right if not isinstance(self.right, ConditionNode) else self.right.to_dict(),
            "children": [c.to_dict() for c in self.children],
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'ConditionNode':
        """Deserialize from dictionary."""
        return cls(
            operator=data["operator"],
            left=cls.from_dict(data["left"]) if isinstance(data["left"], dict) and "operator" in data["left"] else data["left"],
            right=cls.from_dict(data["right"]) if isinstance(data["right"], dict) and "operator" in data["right"] else data["right"],
            children=[cls.from_dict(c) for c in data.get("children", [])],
        )


@dataclass
class StrategyGenome:
    """
    Universal strategy representation.

    This is the canonical format that can be:
    - Generated by any engine (Explorer, LSM, Pattern, etc.)
    - Validated by HIFA v2.0
    - Executed by Hinance forward testing
    - Stored in EMT for production

    Supports conversion to/from:
    - Explorer v3.0 StrategyPosterior
    - LSM token sequences
    - Hinance genome_json
    - Executable Python code
    """

    # Core logic (tree structure)
    entry_conditions: List[Dict[str, Any]]    # When to enter
    exit_conditions: List[Dict[str, Any]]     # When to exit
    position_sizing: Dict[str, Any]           # How much to trade

    # Parameters
    parameters: Dict[str, float]              # Tunable parameters
    lookback_periods: Dict[str, int]          # Data windows

    # Indicators used
    indicators: List[str]                     # ["RSI", "MACD", "BB", ...]

    # Risk management
    stop_loss_pct: Optional[float] = None     # Stop loss percentage
    take_profit_pct: Optional[float] = None   # Take profit percentage
    max_position_size: float = 1.0            # Maximum position (0-1)

    # Complexity metrics (computed)
    n_parameters: int = field(init=False)
    n_rules: int = field(init=False)
    tree_depth: int = field(init=False)

    def __post_init__(self):
        """Compute derived metrics."""
        self.n_parameters = len(self.parameters)
        self.n_rules = len(self.entry_conditions) + len(self.exit_conditions)
        self.tree_depth = self._calculate_depth()

    def _calculate_depth(self) -> int:
        """Calculate max depth of condition tree."""
        def depth(node: Any) -> int:
            if isinstance(node, dict):
                if 'children' in node and node['children']:
                    return 1 + max(depth(c) for c in node['children'])
                elif 'left' in node or 'right' in node:
                    left_depth = depth(node.get('left', {}))
                    right_depth = depth(node.get('right', {}))
                    return 1 + max(left_depth, right_depth)
            return 1

        max_depth = 0
        for cond in self.entry_conditions + self.exit_conditions:
            max_depth = max(max_depth, depth(cond))
        return max_depth

    def compute_hash(self) -> str:
        """Compute unique hash for the genome."""
        content = json.dumps({
            "entry": self.entry_conditions,
            "exit": self.exit_conditions,
            "sizing": self.position_sizing,
            "params": self.parameters,
            "indicators": sorted(self.indicators),
        }, sort_keys=True)
        return hashlib.sha256(content.encode()).hexdigest()[:16]

    def to_json(self) -> str:
        """Serialize to JSON for storage/transmission."""
        return json.dumps({
            "entry_conditions": self.entry_conditions,
            "exit_conditions": self.exit_conditions,
            "position_sizing": self.position_sizing,
            "parameters": self.parameters,
            "lookback_periods": self.lookback_periods,
            "indicators": self.indicators,
            "stop_loss_pct": self.stop_loss_pct,
            "take_profit_pct": self.take_profit_pct,
            "max_position_size": self.max_position_size,
        }, indent=2)

    @classmethod
    def from_json(cls, json_str: str) -> 'StrategyGenome':
        """Deserialize from JSON."""
        data = json.loads(json_str)
        return cls(
            entry_conditions=data["entry_conditions"],
            exit_conditions=data["exit_conditions"],
            position_sizing=data["position_sizing"],
            parameters=data["parameters"],
            lookback_periods=data["lookback_periods"],
            indicators=data["indicators"],
            stop_loss_pct=data.get("stop_loss_pct"),
            take_profit_pct=data.get("take_profit_pct"),
            max_position_size=data.get("max_position_size", 1.0),
        )

    def to_executable(self, language: str = "python") -> str:
        """Generate executable trading code."""
        if language == "python":
            return self._to_python()
        raise ValueError(f"Unsupported language: {language}")

    def _to_python(self) -> str:
        """Generate Python trading code."""
        lines = [
            "# Auto-generated strategy code",
            "# DO NOT EDIT MANUALLY",
            "",
            "from typing import Dict, Any",
            "import numpy as np",
            "",
            "class GeneratedStrategy:",
            "    '''Strategy generated from genome.'''",
            "",
            f"    INDICATORS = {self.indicators}",
            f"    PARAMETERS = {self.parameters}",
            f"    LOOKBACKS = {self.lookback_periods}",
            "",
            "    def __init__(self):",
            f"        self.stop_loss = {self.stop_loss_pct}",
            f"        self.take_profit = {self.take_profit_pct}",
            f"        self.max_position = {self.max_position_size}",
            "",
            "    def should_enter(self, features: Dict[str, Any]) -> bool:",
            "        '''Check entry conditions.'''",
            f"        # Entry rules: {len(self.entry_conditions)}",
            "        return self._evaluate_conditions(features, 'entry')",
            "",
            "    def should_exit(self, features: Dict[str, Any]) -> bool:",
            "        '''Check exit conditions.'''",
            f"        # Exit rules: {len(self.exit_conditions)}",
            "        return self._evaluate_conditions(features, 'exit')",
            "",
            "    def get_position_size(self, features: Dict[str, Any]) -> float:",
            "        '''Calculate position size.'''",
            f"        # Sizing method: {self.position_sizing.get('method', 'fixed')}",
            "        return min(self._calculate_size(features), self.max_position)",
        ]
        return "\n".join(lines)

    def validate(self) -> Tuple[bool, List[str]]:
        """Validate genome structure."""
        errors = []

        # Check required fields
        if not self.entry_conditions:
            errors.append("No entry conditions defined")
        if not self.exit_conditions:
            errors.append("No exit conditions defined")
        if not self.indicators:
            errors.append("No indicators specified")

        # Check complexity limits
        from .constants import (
            MAX_STRATEGY_PARAMETERS,
            MAX_STRATEGY_RULES,
            MAX_STRATEGY_TREE_DEPTH,
            MAX_STRATEGY_INDICATORS,
        )

        if self.n_parameters > MAX_STRATEGY_PARAMETERS:
            errors.append(f"Too many parameters: {self.n_parameters} > {MAX_STRATEGY_PARAMETERS}")
        if self.n_rules > MAX_STRATEGY_RULES:
            errors.append(f"Too many rules: {self.n_rules} > {MAX_STRATEGY_RULES}")
        if self.tree_depth > MAX_STRATEGY_TREE_DEPTH:
            errors.append(f"Tree too deep: {self.tree_depth} > {MAX_STRATEGY_TREE_DEPTH}")
        if len(self.indicators) > MAX_STRATEGY_INDICATORS:
            errors.append(f"Too many indicators: {len(self.indicators)} > {MAX_STRATEGY_INDICATORS}")

        return len(errors) == 0, errors


# ==============================================================================
# Validation Results
# ==============================================================================

@dataclass
class GateResult:
    """Result from a single HIFA gate."""
    gate_number: int
    gate_name: str
    passed: bool
    score: float
    threshold: float
    details: Dict[str, Any] = field(default_factory=dict)
    execution_time_ms: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "gate_number": self.gate_number,
            "gate_name": self.gate_name,
            "passed": self.passed,
            "score": self.score,
            "threshold": self.threshold,
            "details": self.details,
            "execution_time_ms": self.execution_time_ms,
        }


@dataclass
class StatisticalScores:
    """Statistical validation scores from HIFA."""
    dsr: float                        # Deflated Sharpe Ratio
    dsr_pvalue: float                 # DSR p-value
    pbo: float                        # Probability of Backtest Overfitting
    pbo_logits: float                 # PBO logit transform
    t_stat: float                     # Strategy t-statistic
    fdr_adjusted_pvalue: float        # FDR-adjusted p-value
    cpcv_sharpe_mean: float           # Mean Sharpe across CPCV paths
    cpcv_sharpe_std: float            # Std Sharpe across CPCV paths
    cpcv_paths_passed: int            # Number of passing CPCV paths
    cpcv_total_paths: int             # Total CPCV paths tested


@dataclass
class BacktestMetrics:
    """Backtest performance metrics."""
    sharpe_ratio: float
    sortino_ratio: float
    max_drawdown: float
    calmar_ratio: float
    win_rate: float
    profit_factor: float
    total_trades: int
    avg_trade_return: float
    avg_trade_duration_hours: float
    start_date: datetime
    end_date: datetime
    total_return: float


@dataclass
class HIFAResult:
    """Complete HIFA v2.0 validation result."""
    strategy_id: str
    passed: bool
    final_gate: int                   # Last gate passed (1-7)
    gate_results: Dict[int, GateResult]
    statistical_scores: Optional[StatisticalScores]
    backtest_metrics: Optional[BacktestMetrics]
    regime_tier: RegimeTier
    regime_performance: Dict[str, float]  # Sharpe per regime
    cluster_id: Optional[int]         # HRP cluster assignment
    similarity_score: Optional[float]  # Max similarity to existing strategies
    rejection_reason: Optional[str]
    validation_timestamp: datetime = field(default_factory=datetime.now)
    total_execution_time_ms: float = 0.0

    @property
    def backtest_sharpe(self) -> float:
        """Convenience accessor for backtest Sharpe."""
        if self.backtest_metrics:
            return self.backtest_metrics.sharpe_ratio
        return 0.0

    @property
    def backtest_max_dd(self) -> float:
        """Convenience accessor for backtest max drawdown."""
        if self.backtest_metrics:
            return self.backtest_metrics.max_drawdown
        return 1.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "strategy_id": self.strategy_id,
            "passed": self.passed,
            "final_gate": self.final_gate,
            "gate_results": {k: v.to_dict() for k, v in self.gate_results.items()},
            "backtest_sharpe": self.backtest_sharpe,
            "backtest_max_dd": self.backtest_max_dd,
            "regime_tier": self.regime_tier.value,
            "rejection_reason": self.rejection_reason,
            "validation_timestamp": self.validation_timestamp.isoformat(),
        }


# ==============================================================================
# Forward Testing Results
# ==============================================================================

@dataclass
class ShadowMetrics:
    """Shadow/paper trading performance metrics."""
    sharpe_ratio: float
    sortino_ratio: float
    max_drawdown: float
    win_rate: float
    total_trades: int
    avg_slippage_bps: float
    avg_latency_ms: float
    total_fees_paid: float
    start_date: datetime
    end_date: datetime
    duration_days: int
    total_return: float


@dataclass
class ForwardTestResult:
    """Complete forward testing result."""
    strategy_id: str
    passed: bool
    shadow_metrics: ShadowMetrics
    transfer_ratio: float             # shadow_sharpe / backtest_sharpe
    dd_ratio: float                   # shadow_dd / backtest_dd
    rejection_reason: Optional[str]
    backtest_sharpe: float            # Reference from HIFA
    backtest_max_dd: float            # Reference from HIFA
    test_start: datetime
    test_end: datetime

    @property
    def shadow_sharpe(self) -> float:
        return self.shadow_metrics.sharpe_ratio

    @property
    def shadow_max_dd(self) -> float:
        return self.shadow_metrics.max_drawdown

    def to_dict(self) -> Dict[str, Any]:
        return {
            "strategy_id": self.strategy_id,
            "passed": self.passed,
            "transfer_ratio": self.transfer_ratio,
            "dd_ratio": self.dd_ratio,
            "shadow_sharpe": self.shadow_sharpe,
            "shadow_max_dd": self.shadow_max_dd,
            "backtest_sharpe": self.backtest_sharpe,
            "rejection_reason": self.rejection_reason,
            "test_duration_days": self.shadow_metrics.duration_days,
        }


# ==============================================================================
# Unified Strategy (Complete Package)
# ==============================================================================

@dataclass
class UnifiedStrategy:
    """
    Complete strategy package that flows through entire pipeline.

    This is the central data structure that carries a strategy from
    generation through validation to production.
    """

    # Identity
    strategy_id: str = field(default_factory=lambda: f"strat_{uuid.uuid4().hex[:12]}")
    version: str = "1.0"

    # Core content
    genome: Optional[StrategyGenome] = None

    # Provenance
    source_engine: SourceEngine = SourceEngine.MANUAL
    generation_timestamp: datetime = field(default_factory=datetime.now)
    parent_strategies: List[str] = field(default_factory=list)  # For recombination

    # Conditioning (what market state it was designed for)
    target_regime: Optional[str] = None       # "normal", "elevated", "crisis"
    target_volatility: Optional[str] = None   # "low", "medium", "high"
    target_asset: str = "BTCUSDT"

    # Validation state (updated as it passes gates)
    status: StrategyStatus = StrategyStatus.GENERATED
    hifa_result: Optional[HIFAResult] = None
    forward_result: Optional[ForwardTestResult] = None

    # Production state
    production_start: Optional[datetime] = None
    production_end: Optional[datetime] = None
    retirement_reason: Optional[str] = None

    # Metadata
    metadata: Dict[str, Any] = field(default_factory=dict)
    tags: List[str] = field(default_factory=list)

    @property
    def is_hifa_validated(self) -> bool:
        """Check if strategy passed HIFA validation."""
        return self.hifa_result is not None and self.hifa_result.passed

    @property
    def is_forward_validated(self) -> bool:
        """Check if strategy passed forward testing."""
        return self.forward_result is not None and self.forward_result.passed

    @property
    def is_production_ready(self) -> bool:
        """Check if strategy is ready for production."""
        return self.is_hifa_validated and self.is_forward_validated

    @property
    def genome_hash(self) -> Optional[str]:
        """Get genome hash for deduplication."""
        if self.genome:
            return self.genome.compute_hash()
        return None

    def update_status(self, new_status: StrategyStatus):
        """Update strategy status with validation."""
        valid_transitions = {
            StrategyStatus.GENERATED: [StrategyStatus.HIFA_VALIDATING],
            StrategyStatus.HIFA_VALIDATING: [StrategyStatus.HIFA_PASSED, StrategyStatus.HIFA_FAILED],
            StrategyStatus.HIFA_PASSED: [StrategyStatus.SHADOW_TRADING],
            StrategyStatus.HIFA_FAILED: [],  # Terminal
            StrategyStatus.SHADOW_TRADING: [StrategyStatus.FORWARD_PASSED, StrategyStatus.FORWARD_FAILED],
            StrategyStatus.FORWARD_PASSED: [StrategyStatus.PRODUCTION],
            StrategyStatus.FORWARD_FAILED: [],  # Terminal
            StrategyStatus.PRODUCTION: [StrategyStatus.MONITORING, StrategyStatus.RETIRED],
            StrategyStatus.MONITORING: [StrategyStatus.PRODUCTION, StrategyStatus.RETIRED],
            StrategyStatus.RETIRED: [],  # Terminal
        }

        if new_status not in valid_transitions.get(self.status, []):
            raise ValueError(f"Invalid status transition: {self.status} -> {new_status}")

        self.status = new_status

    def attach_hifa_result(self, result: HIFAResult):
        """Attach HIFA validation result."""
        self.hifa_result = result
        if result.passed:
            self.status = StrategyStatus.HIFA_PASSED
        else:
            self.status = StrategyStatus.HIFA_FAILED

    def attach_forward_result(self, result: ForwardTestResult):
        """Attach forward testing result."""
        self.forward_result = result
        if result.passed:
            self.status = StrategyStatus.FORWARD_PASSED
        else:
            self.status = StrategyStatus.FORWARD_FAILED

    def promote_to_production(self):
        """Promote strategy to production status."""
        if not self.is_production_ready:
            raise ValueError("Strategy must pass both HIFA and forward testing")
        self.status = StrategyStatus.PRODUCTION
        self.production_start = datetime.now()

    def retire(self, reason: str):
        """Retire strategy from production."""
        self.status = StrategyStatus.RETIRED
        self.production_end = datetime.now()
        self.retirement_reason = reason

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "strategy_id": self.strategy_id,
            "version": self.version,
            "genome_hash": self.genome_hash,
            "source_engine": self.source_engine.value,
            "generation_timestamp": self.generation_timestamp.isoformat(),
            "target_asset": self.target_asset,
            "target_regime": self.target_regime,
            "status": self.status.value,
            "is_hifa_validated": self.is_hifa_validated,
            "is_forward_validated": self.is_forward_validated,
            "is_production_ready": self.is_production_ready,
            "tags": self.tags,
        }

    def to_json(self) -> str:
        """Serialize to JSON."""
        data = self.to_dict()
        if self.genome:
            data["genome"] = json.loads(self.genome.to_json())
        if self.hifa_result:
            data["hifa_result"] = self.hifa_result.to_dict()
        if self.forward_result:
            data["forward_result"] = self.forward_result.to_dict()
        return json.dumps(data, indent=2, default=str)

    @classmethod
    def from_json(cls, json_str: str) -> 'UnifiedStrategy':
        """Deserialize from JSON."""
        data = json.loads(json_str)

        genome = None
        if "genome" in data:
            genome = StrategyGenome.from_json(json.dumps(data["genome"]))

        return cls(
            strategy_id=data["strategy_id"],
            version=data.get("version", "1.0"),
            genome=genome,
            source_engine=SourceEngine(data.get("source_engine", "manual")),
            target_asset=data.get("target_asset", "BTCUSDT"),
            target_regime=data.get("target_regime"),
            status=StrategyStatus(data.get("status", "generated")),
            tags=data.get("tags", []),
        )


# ==============================================================================
# Production Strategy (Final Format)
# ==============================================================================

@dataclass
class ProductionStrategy:
    """
    Production-ready strategy with all validation complete.

    This is the final format stored in EMT for active trading.
    """
    strategy_id: str
    genome: StrategyGenome
    backtest_metrics: BacktestMetrics
    shadow_metrics: ShadowMetrics
    transfer_ratio: float
    regime_tier: RegimeTier
    cluster_id: int

    # Production tracking
    production_start: datetime
    status: str = "active"            # "active", "monitoring", "retired"

    # Performance tracking
    live_trades: int = 0
    live_sharpe: Optional[float] = None
    live_max_dd: Optional[float] = None
    last_trade_time: Optional[datetime] = None

    # Metadata
    source_engine: str = "unknown"
    tags: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "strategy_id": self.strategy_id,
            "transfer_ratio": self.transfer_ratio,
            "regime_tier": self.regime_tier.value,
            "cluster_id": self.cluster_id,
            "production_start": self.production_start.isoformat(),
            "status": self.status,
            "live_trades": self.live_trades,
            "live_sharpe": self.live_sharpe,
            "source_engine": self.source_engine,
        }
